export const ACTION = {
    // SET_CATEGORIES: 'setCategoriesMap', // old way e. 169
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCES: 'FETCH_CATEGORIES_SUCCES',
    FETCH_CATEGORIES_Failed: 'FETCH_CATEGORIES_Failed',
};